name: spark_dl
channels:
  - rapidsai
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - nvtabular
  - python>=3.7
  - cudatoolkit=11.2
  - cudf>=21.10.*
  - dask-cuda>=21.10.*
  - dask-cudf>=21.10.*
  - rmm>=21.10.*
  - dask==2021.9.1
  - distributed>=2021.9.1
  - fsspec>=0.6.0
  - nvtx>=0.2.1
  - numba>=0.53.0
  - dlpack
  - scikit-learn
  - asvdb
  - pynvml
  - cmake
  - cudnn
  - cxx-compiler
  - nccl
  - nvcc_linux-64
  - openmpi
  - pip
